name: Day 1 CI

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Environment information
        run: |
          echo "User:"
          whoami

          echo "Home:"
          echo $HOME

          echo "Workspace:"
          echo $GITHUB_WORKSPACE

      - name: Checkout
        uses: actions/checkout@v6

      - name: Runner information
        run: |
          echo "Operating system:"
          uname -a

      - name: Current directory
        run: pwd

      - name: Repository files
        run: ls -la

      - name: Validate
        run: exit 1
