name: Day 1 CI

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo "created by validate" > validate.txt

  test:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat validate.txt

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Build"
